### ISSUE TITLE
Constructor de pedidos

### ISSUE THREAD

**Issue by guille31794** [guilogar/poo#3]
```
if(lg->f_expir() < fp) { nle++; continue; }
            pedido_articulo.pedir(*this, *lg, precio, cantidad); //¿Si están expirados los pides igualmente?
        }
        total_ += precio * cantidad;
    }
if(na == 0 && nle > 0) throw Vacio(u); //No tiene porque estar vacío
```

Si tienes un pedido con varios Ebooks distintos, y ningun articulo almacenable, y algunos de los ebooks están expirados, salvo 1 (caso completamente inventado para el ejemplo), están creando items pedido con esos ebooks, y no deberías hacerlo, ¿no?

Después, en el mismo caso, tendrias que na = 0, porque solo compras ebooks, y ademas tendrías al menos un expirado, con lo que nle > 0, pero seguirías teniendo un ebook en tu pedido que no está expirado, habiendo uno, no hay porqué lanzar excepción, ya que el carro no está vacío.

**Comment by guilogar** [comment]
Tienes razón salvo en una cosa. Para empezar, si te fijas, dentro del "if" tiene un "continue", por lo cual, si el ebook esta expirado, no pasara a la siguiente linea donde añade el ebook. Y segundo, la excepción salta si no había ningún ArticuloAlmacenable y todos eran ebooks caducados. Es decir, habría que comprobar que "nle" sea igual al numero total de ebooks. Me pondré a ello en cuanto pueda.
